# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('from_date_and_time', models.DateTimeField(default=datetime.datetime(2016, 6, 19, 6, 20, 11, 150109, tzinfo=utc), verbose_name='Start')),
                ('to_date_and_time', models.DateTimeField(help_text='Please set end time to later than start time.', verbose_name='End')),
                ('description', models.TextField()),
            ],
        ),
    ]
