# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date(2016, 7, 20), help_text='The end date must be later than the start date', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 7, 20), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(default=datetime.date(2016, 7, 20), null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='project_task_date',
            field=models.DateField(default=datetime.date(2016, 7, 20), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.date(2016, 7, 20), null=True),
        ),
    ]
