# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 19, 8, 18, 39, 980560, tzinfo=utc), verbose_name='Start'),
        ),
    ]
