# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0002_auto_20160718_0047'),
        ('MyCalendar', '0002_auto_20160717_2117'),
    ]

    operations = [
    ]
