# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0003_auto_20160622_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date(2016, 6, 22), help_text='The end date must be later than the start date', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='The end must be later than the start ', null=True),
        ),
    ]
