# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-20 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0004_auto_20160620_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='from_date_and_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='to_date_and_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date(2016, 6, 20)),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.date(2016, 6, 20)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 6, 20)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.date(2016, 6, 20)),
        ),
    ]
